const cfg = window.MOTIVA_CONFIG || {};
const app = document.getElementById('app');
const LEVELS = ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'];
const COURSE_PREVIEWS = {
  A1: { label: 'Découverte', outcome: 'Understand and use everyday French from the first exchange.', focus: 'Greetings, alphabet, numbers, dates, time and daily survival language.', accent: 'blue' },
  A2: { label: 'Élan', outcome: 'Handle familiar situations and tell simple connected stories.', focus: 'Everyday life, travel, work, health and practical communication.', accent: 'rose' },
  B1: { label: 'Passerelle', outcome: 'Express experiences, opinions and plans with growing independence.', focus: 'Narrative, opinion, culture, work and real-world discussion.', accent: 'gold' },
  B2: { label: 'Perspective', outcome: 'Argue, negotiate and understand complex points of view.', focus: 'Debate, nuance, media, society and academic-style communication.', accent: 'blue' },
  C1: { label: 'Nuance', outcome: 'Use French flexibly, precisely and fluently in demanding contexts.', focus: 'Register, inference, professional writing and complex discourse.', accent: 'rose' },
  C2: { label: 'Maîtrise', outcome: 'Mediate, synthesize and express subtle meaning with control.', focus: 'Rhetoric, precision, source comparison and high-level production.', accent: 'gold' },
};
const state = {
  session: null, me: null, plan: null, courseCache: new Map(), assetUrls: new Map(), activeAudio: null,
  tcf: null, grammar: null, admin: null, users: [], notice: '', builders: new Map(), progress: null,
};
const SESSION_KEY = 'motiva-independent-session-v1';
const PROGRESS_PREFIX = 'motiva-learning-progress-ui-v2';
const esc = (value = '') => String(value ?? '').replace(/[&<>'"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c]));
const fmt = (value = '') => esc(String(value ?? '')).replace(/\n/g, '<br>');
const money = (cents, currency) => new Intl.NumberFormat('fr-FR', { style: 'currency', currency: currency || 'EGP' }).format((Number(cents) || 0) / 100);
const edgeBase = String(cfg.apiBase || (cfg.supabaseUrl ? `${cfg.supabaseUrl}/functions/v1/motiva-api` : '')).replace(/\/$/, '');
const apiUrl = (pathname) => `${edgeBase}${String(pathname).replace(/^\/api/, '')}`;
const route = () => location.hash.slice(1) || 'today';
const go = (target) => { location.hash = target; };
const sessionHeaders = () => state.session?.access_token ? { Authorization: `Bearer ${state.session.access_token}` } : {};
const isActive = () => Boolean(state.me?.access?.active);
const isAdmin = () => state.me?.user?.role === 'admin';

function setNotice(message, kind = 'success') { state.notice = message ? `<p class="${kind}">${esc(message)}</p>` : ''; }
function savedSession() { try { return JSON.parse(localStorage.getItem(SESSION_KEY) || 'null'); } catch { return null; } }
function saveSession(value) { state.session = value; if (value) localStorage.setItem(SESSION_KEY, JSON.stringify(value)); else localStorage.removeItem(SESSION_KEY); }
function progressKey() { return `${PROGRESS_PREFIX}:${state.me?.user?.id || 'visitor'}`; }
function freshProgress() { return { lessons: {}, lastLesson: null, updatedAt: null }; }
function loadProgress() { try { state.progress = JSON.parse(localStorage.getItem(progressKey()) || 'null') || freshProgress(); } catch { state.progress = freshProgress(); } }
function saveProgress() { if (!state.progress) return; state.progress.updatedAt = new Date().toISOString(); localStorage.setItem(progressKey(), JSON.stringify(state.progress)); }
function lessonKey(level, unit) { return `${level}-${String(unit).padStart(2, '0')}`; }
function lessonProgress(level, unit) { const key = lessonKey(level, unit); state.progress ||= freshProgress(); return state.progress.lessons[key] ||= { started: false, completed: false, correct: {}, lastStage: 'discover', updatedAt: null }; }
function touchLesson(level, unit, stage = null) { const record = lessonProgress(level, unit); record.started = true; if (stage) record.lastStage = stage; record.updatedAt = new Date().toISOString(); state.progress.lastLesson = { level, unit: Number(unit), stage: record.lastStage }; saveProgress(); return record; }
function markCorrect(level, unit, exerciseId) { const record = touchLesson(level, unit); record.correct[exerciseId] = true; saveProgress(); }
function markComplete(level, unit) { const record = touchLesson(level, unit, 'review'); record.completed = true; saveProgress(); }
function courseStats(level) { const records = Object.entries(state.progress?.lessons || {}).filter(([key]) => key.startsWith(`${level}-`)).map(([, value]) => value); return { started: records.filter((x) => x.started).length, complete: records.filter((x) => x.completed).length, correct: records.reduce((sum, x) => sum + Object.keys(x.correct || {}).length, 0) }; }
function totalCompleted() { return Object.values(state.progress?.lessons || {}).filter((x) => x.completed).length; }
function nextLesson() { const saved = state.progress?.lastLesson; return saved ? `lesson/${saved.level}/${saved.unit}` : 'lesson/A1/1'; }

async function supabase(pathname, { method = 'GET', body } = {}) {
  if (!cfg.supabaseUrl || !cfg.supabaseAnonKey) throw new Error('Supabase configuration is missing.');
  const response = await fetch(new URL(pathname, cfg.supabaseUrl), { method, headers: { apikey: cfg.supabaseAnonKey, 'Content-Type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body) });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.msg || data.error_description || data.message || 'Authentication request failed.');
  return data;
}
async function refreshSession() { if (!state.session?.refresh_token) return null; const data = await supabase('/auth/v1/token?grant_type=refresh_token', { method: 'POST', body: { refresh_token: state.session.refresh_token } }); saveSession(data); return data; }
async function api(pathname, { method = 'GET', body, retry = true } = {}) {
  if (!edgeBase || !cfg.supabaseAnonKey) throw new Error('Member API configuration is missing.');
  const response = await fetch(apiUrl(pathname), { method, headers: { apikey: cfg.supabaseAnonKey, ...sessionHeaders(), ...(body === undefined ? {} : { 'Content-Type': 'application/json' }) }, body: body === undefined ? undefined : JSON.stringify(body) });
  if (response.status === 401 && retry && state.session?.refresh_token) { await refreshSession(); return api(pathname, { method, body, retry: false }); }
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.error || 'Request failed.');
  return data;
}
async function protectedBlob(key) {
  if (state.assetUrls.has(key)) return state.assetUrls.get(key);
  const response = await fetch(apiUrl(`/api/content/${key}`), { headers: { apikey: cfg.supabaseAnonKey, ...sessionHeaders() } });
  if (!response.ok) throw new Error(response.status === 403 ? 'active_subscription_required' : 'protected_asset_unavailable');
  const url = URL.createObjectURL(await response.blob()); state.assetUrls.set(key, url); return url;
}
async function getMe() { if (!state.session?.access_token) { state.me = null; loadProgress(); return null; } state.me = await api('/api/me'); loadProgress(); return state.me; }
async function getPlan() { state.plan = await api('/api/public/plan'); return state.plan; }
function cover(level) { return `${apiUrl(`/api/public/cover/${level}`)}?apikey=${encodeURIComponent(cfg.supabaseAnonKey || '')}`; }

function header(active = '') {
  const auth = state.me?.user?.email ? esc(state.me.user.email.split('@')[0]) : 'Sign in';
  const links = [['today', 'Today'], ['learn', 'Learn'], ['practice', 'Practice'], ['progress', 'Progress'], ['membership', 'Membership']];
  return `<header class="top"><div class="top-in"><a class="brand" href="#today" aria-label="MOTIVA home"><span class="brand-mark">M</span>MOT<i>I</i>VA</a><nav class="nav" aria-label="Main learning navigation">${links.map(([key, label]) => `<button data-go="${key}" class="${active === key ? 'active' : ''}">${label}</button>`).join('')}${isAdmin() ? `<button data-go="admin" class="${active === 'admin' ? 'active' : ''}">Admin</button>` : ''}</nav><button class="account-button" data-go="${state.me?.user ? 'membership' : 'login'}"><span class="account-dot"></span>${auth}</button></div></header>`;
}
function mobileNav(active = '') {
  const links = [['today', '⌂', 'Today'], ['learn', '◫', 'Learn'], ['practice', '◉', 'Practice'], ['progress', '↗', 'Progress'], ['membership', '◌', 'Account']];
  return `<nav class="mobile-nav" aria-label="Mobile navigation">${links.map(([key, icon, label]) => `<button data-go="${key}" class="${active === key ? 'active' : ''}"><span>${icon}</span>${label}</button>`).join('')}</nav>`;
}
function footer() { return `<footer class="footer shell">MOTIVA · Learn French through use, practice and reflection. Protected content is delivered only after server-side entitlement verification.</footer>`; }
function page(active, body) { return `${header(active)}<main id="main" class="shell">${state.notice}${body}</main>${mobileNav(active)}${footer()}`; }
function lockPanel(copy = 'This learning area is available with an active membership.') { return `<section class="lock-panel"><div class="lock-icon">⌁</div><div><p class="eyebrow">Member lesson</p><h2>Ready when your access is active</h2><p>${esc(copy)}</p><div class="buttons"><button class="button" data-go="membership">View membership</button><button class="button alt" data-go="learn">Browse learning path</button></div></div></section>`; }
function emptyProgress(message) { return `<div class="empty-state"><span>✦</span><h3>Start your first learning session</h3><p>${esc(message)}</p><button class="button" data-go="lesson/A1/1">Begin A1 · Lesson 01</button></div>`; }

function previewCourseCard(level, compact = false) {
  const preview = COURSE_PREVIEWS[level]; const stats = courseStats(level); const percent = Math.min(100, Math.round((stats.complete / 12) * 100));
  return `<article class="course-card ${compact ? 'compact' : ''}"><div class="course-card-top"><span class="level-pill">CEFR ${level}</span><span class="course-state">${stats.complete ? `${stats.complete}/12 complete` : '12 learning units'}</span></div><div class="course-card-copy"><h3>${esc(preview.label)}</h3><p>${esc(preview.outcome)}</p></div><div class="course-meter"><span style="width:${percent}%"></span></div><div class="course-card-foot"><span>${stats.complete ? `${percent}% complete` : esc(preview.focus)}</span><button class="text-button" data-go="course/${level}">Explore →</button></div></article>`;
}
function publicPlatformOverview() {
  return `<section class="welcome-grid"><div><p class="eyebrow">French learning platform · A1–C2</p><h1>Use French.<br><em>Not just books.</em></h1><p class="lead">MOTIVA guides you from the next lesson to meaningful practice: listen, respond, get correction and keep moving.</p><div class="buttons"><button class="button" data-go="login">Create your learning account</button><button class="button alt" data-go="learn">Explore the pathway</button></div><div class="trust-row"><span>✦ CEFR pathway</span><span>◉ Immediate correction</span><span>♬ Protected listening</span></div></div><aside class="welcome-lesson"><div class="mini-progress"><span>YOUR NEXT STEP</span><strong>Lesson 01</strong></div><h2>Say hello with confidence.</h2><p>Listen to a real exchange, build a sentence, and use it immediately.</p><div class="lesson-preview-stack"><span>1 · Discover</span><span>2 · Listen</span><span>3 · Use it</span><span>4 · Checkpoint</span></div><button class="button alt" data-go="learn">See how lessons work</button></aside></section><section class="section intro-path"><div class="section-heading"><div><p class="eyebrow">A clear path</p><h2>Every level has a next useful action.</h2></div><p>Browse the pathway now. Active membership unlocks the protected lessons, sound and interactive practice.</p></div><div class="course-grid">${LEVELS.map((level) => previewCourseCard(level, true)).join('')}</div></section>`;
}
function renderToday() {
  if (!state.me?.user) { app.innerHTML = page('today', publicPlatformOverview()); return; }
  const completed = totalCompleted(); const last = state.progress?.lastLesson; const next = nextLesson(); const focus = last ? `Continue ${last.level} · Lesson ${String(last.unit).padStart(2, '0')}` : 'Begin A1 · Lesson 01';
  const accessLine = isActive() ? 'Your membership is active. Your protected lessons and listening practice are ready.' : 'You can browse the learning path now. Activate membership to open lessons and listening practice.';
  const hero = `<section class="dashboard-hero"><div><p class="eyebrow">Today at MOTIVA</p><h1>${completed ? 'Continue your French.' : 'Your French starts here.'}</h1><p class="lead">${esc(accessLine)}</p><div class="continue-card"><div><span class="continue-kicker">${last ? 'RESUME' : 'START'}</span><h2>${esc(focus)}</h2><p>${isActive() ? 'A short guided session with listening, practice and feedback.' : 'Preview the path now; unlock interactive learning with an active membership.'}</p></div><button class="button" data-go="${isActive() ? next : 'membership'}">${isActive() ? 'Continue learning →' : 'View membership'}</button></div></div><aside class="today-score"><span class="score-orb">${completed}</span><strong>Lessons complete</strong><p>${Object.values(state.progress?.lessons || {}).reduce((sum, x) => sum + Object.keys(x.correct || {}).length, 0)} correct practice responses saved on this device.</p><button class="text-button" data-go="progress">View my progress →</button></aside></section>`;
  const practice = `<section class="section dashboard-grid"><article class="recommendation-card"><p class="eyebrow">Recommended next</p><h2>Practice through use</h2><p>Open a focused unit to hear natural French, retrieve a phrase and use it in context.</p><button class="button alt" data-go="${isActive() ? next : 'learn'}">${isActive() ? 'Open lesson' : 'Explore courses'}</button></article><article class="review-card"><p class="eyebrow">Practice studio</p><h2>TCF & grammar</h2><p>Use interactive practice when you are ready to test comprehension and structure.</p><button class="text-button" data-go="practice">Open Practice →</button></article><article class="membership-card"><p class="eyebrow">Membership</p><h2>${isActive() ? 'Access active' : 'Your access'}</h2><p>${isActive() ? 'All current course lessons, audio and references are protected and available.' : `Manual membership: ${state.plan?.configured ? money(state.plan.priceCents, state.plan.currency) : 'available soon'}.`}</p><button class="text-button" data-go="membership">Manage membership →</button></article></section>`;
  app.innerHTML = page('today', `${hero}${practice}`);
}

function renderLearn() {
  const headerCopy = state.me?.user ? 'Choose a level, then move through clear units and focused lessons.' : 'Explore the full A1–C2 learning pathway. Lesson previews are open; interactive material stays protected until membership is active.';
  app.innerHTML = page('learn', `<section class="page-intro"><p class="eyebrow">Learn French step by step</p><h1>Choose your pathway.</h1><p class="lead">${esc(headerCopy)}</p></section><section class="course-grid full">${LEVELS.map((level) => previewCourseCard(level)).join('')}</section><section class="section learning-explainer"><div><p class="eyebrow">Inside every lesson</p><h2>One small learning loop.<br>Repeated with purpose.</h2></div><ol class="learning-loop"><li><strong>Discover</strong><span>See the situation and the goal.</span></li><li><strong>Listen</strong><span>Hear French in useful context.</span></li><li><strong>Use</strong><span>Choose, fill, match and build.</span></li><li><strong>Reflect</strong><span>Get correction and continue.</span></li></ol></section>`);
}

async function loadCourse(level) {
  if (state.courseCache.has(level)) return state.courseCache.get(level);
  const response = await fetch(apiUrl(`/api/content/courses/${level}/course.json`), { headers: { apikey: cfg.supabaseAnonKey, ...sessionHeaders() } });
  if (!response.ok) throw new Error(response.status === 403 ? 'active_subscription_required' : 'course_not_available');
  const data = await response.json(); state.courseCache.set(level, data); return data;
}
function publicUnitPreview(level) {
  return Array.from({ length: 12 }, (_, index) => `<article class="unit-row locked"><div class="unit-number">${String(index + 1).padStart(2, '0')}</div><div><span>UNIT ${String(index + 1).padStart(2, '0')}</span><h3>Learning session</h3><p>${index === 0 ? COURSE_PREVIEWS[level].focus : 'Course outcome and lesson sequence available after activation.'}</p></div><span class="lock-label">Locked</span></article>`).join('');
}
async function renderCourse(level) {
  const preview = COURSE_PREVIEWS[level];
  if (!state.me?.user || !isActive()) {
    app.innerHTML = page('learn', `<section class="course-hero"><div><button class="crumb" data-go="learn">← All courses</button><p class="eyebrow">CEFR ${level} · ${esc(preview.label)}</p><h1>${esc(preview.outcome)}</h1><p class="lead">${esc(preview.focus)}</p><div class="buttons"><button class="button" data-go="membership">Unlock learning</button><button class="button alt" data-go="learn">All levels</button></div></div><div class="course-visual"><img src="${cover(level)}" alt="MOTIVA ${level} course cover"><span>12 guided units</span></div></section><section class="section"><div class="section-heading"><div><p class="eyebrow">Course preview</p><h2>What you will work through</h2></div><p>Unit and lesson information is visible. Audio, answers and course data remain protected until your membership is active.</p></div><div class="unit-list">${publicUnitPreview(level)}</div></section>`); return;
  }
  try {
    const course = await loadCourse(level); const units = course.units || []; const stats = courseStats(level);
    const rows = units.map((unit, index) => { const record = lessonProgress(level, index + 1); const status = record.completed ? 'Complete' : record.started ? 'In progress' : 'Ready'; return `<button class="unit-row actionable ${record.completed ? 'done' : record.started ? 'current' : ''}" data-go="lesson/${level}/${index + 1}"><div class="unit-number">${String(index + 1).padStart(2, '0')}</div><div><span>${status.toUpperCase()} · ${record.completed ? 'Checkpoint complete' : 'Guided lesson'}</span><h3>${esc(unit.titleFr)}</h3><p>${esc(unit.titleEn || unit.theme || '')}</p></div><div class="unit-meta"><span>${record.completed ? '✓' : record.started ? '↻' : '→'}</span><small>${record.completed ? 'Complete' : record.started ? 'Resume' : 'Start'}</small></div></button>`; }).join('');
    app.innerHTML = page('learn', `<section class="course-hero"><div><button class="crumb" data-go="learn">← All courses</button><p class="eyebrow">Your CEFR ${level} pathway</p><h1>${esc(course.meta?.title || `MOTIVA ${level}`)}</h1><p class="lead">${esc(course.meta?.tagline || preview.outcome)}</p><div class="course-summary"><span><strong>${stats.complete}</strong> / 12 units complete</span><span><strong>${stats.correct}</strong> correct responses</span><span>Progress saved on this device in this UI phase</span></div><div class="buttons"><button class="button" data-go="${nextLesson().startsWith(`lesson/${level}/`) ? nextLesson() : `lesson/${level}/1`}">${stats.started ? 'Continue course →' : 'Start course →'}</button></div></div><div class="course-visual"><img src="${cover(level)}" alt="MOTIVA ${level} course cover"><span>Immersion course · 12 units</span></div></section><section class="section"><div class="section-heading"><div><p class="eyebrow">Learning path</p><h2>One unit at a time.</h2></div><p>Open a focused session. Learn through context, listening, active use and correction.</p></div><div class="unit-list">${rows}</div></section>`);
  } catch (error) { app.innerHTML = page('learn', `<section class="error-state"><h1>Course unavailable</h1><p>${esc(error.message === 'active_subscription_required' ? 'An active membership is needed to load this protected course.' : 'Please try again in a moment.')}</p></section>`); }
}

function audioButton(key, label, className = '') { const normalized = String(key).replace(/\.mp3\.mp3$/i, '.mp3'); return `<button class="audio-control ${className}" data-audio="${esc(normalized)}"><span class="audio-icon">▶</span><span>${esc(label)}</span></button>`; }
function questionCard(question, id, level, unit, kind = 'choice') {
  const prompt = question.questionFr || question.promptFr || question.q || question.prompt || ''; const support = question.questionEn || question.promptEn || '';
  const choices = question.choices || []; const answer = question.answer || '';
  return `<fieldset class="exercise-card" data-answer="${esc(answer)}" data-exercise="${esc(id)}" data-level="${esc(level)}" data-unit="${esc(unit)}"><div class="exercise-label">${esc(kind)}</div><legend>${esc(prompt)}</legend>${support ? `<p class="support">${esc(support)}</p>` : ''}<div class="choice-stack">${choices.map((choice) => `<label class="choice"><input type="radio" name="${esc(id)}" value="${esc(choice)}"><span>${esc(choice)}</span></label>`).join('')}</div><div class="exercise-actions"><button class="button alt" type="button" data-check-mcq>Check answer</button><span class="feedback" aria-live="polite"></span></div><details><summary>Show correction</summary><p><strong>${esc(answer)}</strong></p>${question.explanationFr || question.why ? `<p>${esc(question.explanationFr || question.why)}</p>` : ''}</details></fieldset>`;
}
function fillBlankCard(question, id, level, unit) {
  const prompt = question.promptFr || question.questionFr || ''; const answer = question.answer || '';
  return `<section class="exercise-card fill-card" data-answer="${esc(answer)}" data-exercise="${esc(id)}" data-level="${esc(level)}" data-unit="${esc(unit)}"><div class="exercise-label">Fill the blank</div><h3>${esc(prompt)}</h3><p class="support">${esc(question.promptEn || '')}</p><label class="fill-input"><span>Your answer</span><input type="text" autocomplete="off" placeholder="Écrivez la réponse…"></label><div class="exercise-actions"><button class="button alt" type="button" data-check-fill>Check answer</button><span class="feedback" aria-live="polite"></span></div><details><summary>Show correction</summary><p><strong>${esc(answer)}</strong></p><p>${esc(question.explanationFr || '')}</p></details></section>`;
}
function matchingCard(items, id, level, unit) {
  const options = items.map((item) => item.rightEn).sort(() => .5 - Math.random());
  return `<section class="exercise-card match-card" data-exercise="${esc(id)}" data-level="${esc(level)}" data-unit="${esc(unit)}"><div class="exercise-label">Match meaning</div><h3>Reliez chaque mot à son idée.</h3><p class="support">Match each French item to its meaning.</p><div class="match-grid">${items.map((item, index) => `<label><strong>${esc(item.leftFr)}</strong><select data-match-answer="${esc(item.rightEn)}"><option value="">Choose a meaning…</option>${options.map((opt) => `<option value="${esc(opt)}">${esc(opt)}</option>`).join('')}</select></label>`).join('')}</div><div class="exercise-actions"><button class="button alt" type="button" data-check-match>Check matches</button><span class="feedback" aria-live="polite"></span></div></section>`;
}
function sentenceBuilderCard(item, id, level, unit) {
  state.builders.set(id, { tokens: item.tokens || [], selected: [] });
  return `<section class="exercise-card builder-card" data-exercise="${esc(id)}" data-level="${esc(level)}" data-unit="${esc(unit)}"><div class="exercise-label">Order the words</div><h3>Construisez la phrase.</h3><p class="support">${esc(item.hintEn || 'Put the words in a natural French order.')}</p><div class="builder-output" id="builder-output-${esc(id)}"><span>Tap words to build your sentence.</span></div><div class="token-bank">${(item.tokens || []).map((token, index) => `<button type="button" class="token" data-builder="${esc(id)}" data-token="${index}">${esc(token)}</button>`).join('')}</div><div class="exercise-actions"><button class="button alt" type="button" data-check-order data-builder="${esc(id)}" data-answer="${esc(item.answerFr || '')}">Check order</button><button class="text-button" type="button" data-reset-builder="${esc(id)}">Reset</button><span class="feedback" aria-live="polite"></span></div><details><summary>Show model sentence</summary><p><strong>${esc(item.answerFr || '')}</strong></p></details></section>`;
}
function dictationCard(item, id, level, unit) {
  return `<section class="exercise-card dictation-card" data-exercise="${esc(id)}" data-level="${esc(level)}" data-unit="${esc(unit)}" data-answer="${esc(item.answerFr || '')}"><div class="exercise-label">Listen & write</div><h3>${esc(item.promptFr || 'Écoutez et écrivez.')}</h3><p class="support">${esc(item.promptEn || '')}</p>${audioButton(`courses/${level}/audio/${item.audioRef || ''}.mp3`, 'Play dictation')}<label class="fill-input"><span>What did you hear?</span><textarea placeholder="Écrivez en français…"></textarea></label><div class="exercise-actions"><button class="button alt" type="button" data-check-dictation>Check writing</button><span class="feedback" aria-live="polite"></span></div><details><summary>Show transcript</summary><p><strong>${esc(item.answerFr || '')}</strong></p></details></section>`;
}
function imageSlot(key, alt) { return `<img data-asset="${esc(key)}" alt="${esc(alt)}" class="lesson-image" src="data:image/gif;base64,R0lGODlhAQABAAAAACw="/>`; }
function stageButton(stage, label, current) { return `<button class="lesson-step ${stage === current ? 'active' : ''}" data-stage="${stage}">${esc(label)}</button>`; }
function normalText(value) { return String(value || '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/gi, ' ').trim(); }
function sentenceFrom(tokens) { return tokens.join(' ').replace(/\s+([,.;:?!])/g, '$1').replace(/([«])\s+/g, '$1').replace(/\s+([»])/g, '$1').trim(); }

function lessonStageContent(stage, u, level, unit) {
  const base = `courses/${level}`; const idBase = `${level}-${unit}`;
  if (stage === 'discover') {
    const cards = (u.immersion?.recallCards || u.foundation?.cards || []).slice(0, 6).map((card, index) => `<button class="recall-card" data-flip-card><span class="recall-front">${esc(card.frontFr || '')}</span><span class="recall-back"><strong>${esc(card.backEn || '')}</strong><small>${esc(card.backAr || '')}</small><em>${esc(card.exampleFr || '')}</em></span></button>`).join('');
    return `<section class="lesson-panel"><div class="panel-head"><div><p class="eyebrow">Discover</p><h2>${esc(u.immersion?.visualContext?.titleFr || u.foundation?.titleFr || 'Your learning map')}</h2></div><span class="time-pill">5 min</span></div><p>${esc(u.opener || u.immersion?.visualContext?.promptFr || '')}</p><div class="goal-list">${(u.goals || []).slice(0, 3).map((goal) => `<span>✓ ${esc(typeof goal === 'string' ? goal : goal.fr || goal.text || '')}</span>`).join('')}</div><div class="recall-grid">${cards}</div><div class="lesson-continue"><button class="button" data-stage-next="listen">Continue to listening →</button></div></section>`;
  }
  if (stage === 'listen') {
    const lines = (u.dialogue?.lines || []).map((line) => `<article class="dialogue-bubble"><span>${esc(line.speaker || '')}</span><p>${esc(line.fr || '')}</p><small>${esc(line.en || '')}</small></article>`).join('');
    const questions = (u.listening?.items || []).slice(0, 2).map((q, index) => questionCard(q, `${idBase}-listen-${index}`, level, unit, 'Listening check')).join('');
    return `<section class="lesson-panel"><div class="panel-head"><div><p class="eyebrow">Listen</p><h2>${esc(u.dialogue?.titleFr || 'Hear French in context')}</h2></div><span class="time-pill">6 min</span></div><p>${esc(u.dialogue?.titleEn || 'Listen first, then notice the useful phrases.')}</p><div class="audio-deck">${audioButton(`${base}/audio/${u.id}-dialogue.mp3`, 'Play dialogue', 'primary')}${audioButton(`${base}/audio/${u.id}-dialogue-slow.mp3`, 'Slow speed')}</div><div class="dialogue-stack">${lines}</div><div class="practice-divider"><span>Check what you heard</span></div>${questions}<div class="lesson-continue"><button class="button" data-stage-next="use">Use the language →</button></div></section>`;
  }
  if (stage === 'use') {
    const fill = (u.guidedPractice || []).slice(0, 1).map((q, index) => fillBlankCard(q, `${idBase}-fill-${index}`, level, unit)).join('');
    const matching = u.immersion?.matching?.length ? matchingCard(u.immersion.matching, `${idBase}-match`, level, unit) : '';
    const builder = (u.immersion?.sentenceBuilds || []).slice(0, 1).map((item, index) => sentenceBuilderCard(item, `${idBase}-order-${index}`, level, unit)).join('');
    const dictation = u.immersion?.dictation ? dictationCard(u.immersion.dictation, `${idBase}-dictation`, level, unit) : '';
    return `<section class="lesson-panel"><div class="panel-head"><div><p class="eyebrow">Use it</p><h2>Make the language yours.</h2></div><span class="time-pill">8 min</span></div><p>Work through short actions: fill, match, order and write. You will get feedback after each attempt.</p>${fill}${matching}${builder}${dictation}<div class="lesson-continue"><button class="button" data-stage-next="checkpoint">Go to checkpoint →</button></div></section>`;
  }
  if (stage === 'checkpoint') {
    const test = (u.unitTest || []).slice(0, 5).map((q, index) => questionCard(q, `${idBase}-check-${index}`, level, unit, 'Checkpoint')).join('');
    return `<section class="lesson-panel"><div class="panel-head"><div><p class="eyebrow">Checkpoint</p><h2>Check your understanding.</h2></div><span class="time-pill">7 min</span></div><p>Use the feedback after each question. Finish when you feel ready, then record the lesson as complete.</p>${test}<div class="lesson-complete-card"><div><strong>Ready to close this lesson?</strong><p>You can return at any time for review.</p></div><button class="button" data-complete-lesson>Complete lesson ✓</button></div></section>`;
  }
  const readingQuestions = (u.reading?.questions || []).slice(0, 2).map((q, index) => questionCard(q, `${idBase}-read-${index}`, level, unit, 'Reading check')).join('');
  const referenceType = level === 'A1' || level === 'A2' ? 'books/grammar.pdf' : 'books/tcf.pdf'; const referenceLabel = level === 'A1' || level === 'A2' ? 'Open grammar reference in MOTIVA' : 'Open TCF reference in MOTIVA';
  return `<section class="lesson-panel"><div class="panel-head"><div><p class="eyebrow">Review & reflect</p><h2>Use it beyond the exercise.</h2></div><span class="time-pill">5 min</span></div><article class="reading-card"><h3>${esc(u.reading?.titleFr || 'Read in context')}</h3><p>${fmt(u.reading?.textFr || '')}</p></article>${readingQuestions}<article class="transfer-card"><span>Say it</span><h3>${esc(u.challenge?.taskFr || u.speaking?.taskFr || '')}</h3><p class="support">${esc(u.challenge?.taskEn || u.speaking?.taskEn || '')}</p></article><article class="reference-card"><div><p class="eyebrow">Go deeper</p><h3>Reference for this lesson</h3><p>The source book remains protected and opens inside this platform only after access is checked.</p></div><button class="button alt" data-reference="${referenceType}" data-reference-title="${esc(referenceLabel)}">${esc(referenceLabel)}</button></article><div class="lesson-continue"><button class="button" data-complete-lesson>Mark lesson complete ✓</button></div></section>`;
}
async function renderLesson(level, unitNumber, stageParam = null) {
  if (!state.me?.user) { app.innerHTML = page('learn', lockPanel('Create an account to keep track of your learning path.')); return; }
  if (!isActive()) { app.innerHTML = page('learn', lockPanel('Your account can see the course path. An active membership is required before protected lessons, audio and answers are delivered.')); return; }
  try {
    const course = await loadCourse(level); const units = course.units || []; const index = Math.max(0, Math.min(units.length - 1, Number(unitNumber) - 1)); const unit = index + 1; const u = units[index]; const record = touchLesson(level, unit); const stage = ['discover', 'listen', 'use', 'checkpoint', 'review'].includes(stageParam) ? stageParam : record.lastStage || 'discover'; record.lastStage = stage; saveProgress(); state.builders = new Map();
    const imageName = `${(u.id || '').replace(/^.*u/, 'u') || `u${String(unit).padStart(2, '0')}`}.png`; const prev = unit > 1 ? `<button class="text-button" data-go="lesson/${level}/${unit - 1}">← Previous lesson</button>` : `<button class="text-button" data-go="course/${level}">← Course overview</button>`; const next = unit < units.length ? `<button class="text-button" data-go="lesson/${level}/${unit + 1}">Next lesson →</button>` : `<button class="text-button" data-go="progress">See my progress →</button>`;
    app.innerHTML = page('learn', `<div class="lesson-topbar"><button class="crumb" data-go="course/${level}">← ${esc(course.meta?.title || `MOTIVA ${level}`)}</button><div>${prev}${next}</div></div><section class="lesson-hero"><div><p class="eyebrow">Unit ${String(unit).padStart(2, '0')} · ${esc(u.theme || '')}</p><h1>${esc(u.titleFr)}</h1><p class="lead">${esc(u.titleEn || '')}</p><div class="lesson-goal">${esc((u.goals || [])[0] || 'Use French in a meaningful real-life context.')}</div></div>${imageSlot(`courses/${level}/images/${imageName}`, u.theme || u.titleFr)}</section><nav class="lesson-steps" aria-label="Lesson stages">${stageButton('discover', '1 Discover', stage)}${stageButton('listen', '2 Listen', stage)}${stageButton('use', '3 Use', stage)}${stageButton('checkpoint', '4 Check', stage)}${stageButton('review', '5 Review', stage)}</nav>${lessonStageContent(stage, u, level, unit)}`);
    hydrateImages();
  } catch (error) { app.innerHTML = page('learn', `<section class="error-state"><h1>Lesson unavailable</h1><p>${esc(error.message === 'active_subscription_required' ? 'An active membership is required to open this protected lesson.' : 'Please retry in a moment.')}</p></section>`); }
}

async function hydrateImages() { for (const node of app.querySelectorAll('img[data-asset]')) { try { node.src = await protectedBlob(node.dataset.asset); } catch { node.alt = 'Protected lesson image unavailable'; } } }

function renderPractice() {
  const access = isActive(); const cards = [['tcf', 'TCF Lab', 'Train comprehension and structures with corrected dossiers.', 'Targeted practice'], ['grammar', 'Grammar Studio', 'Use French structures, then verify them immediately.', 'Guided drills'], ['review', 'Quick Review', 'Return to completed lessons and keep useful language active.', 'Personal review']];
  app.innerHTML = page('practice', `<section class="page-intro"><p class="eyebrow">Practice with purpose</p><h1>Choose how you want to train.</h1><p class="lead">TCF, grammar and review are practice spaces—not static books. Each activity keeps correction close to the attempt.</p></section><section class="practice-grid-platform">${cards.map(([key, title, copy, label]) => `<article class="practice-tile"><span>${esc(label)}</span><h2>${esc(title)}</h2><p>${esc(copy)}</p><button class="button ${access ? '' : 'alt'}" data-go="${key === 'review' ? 'progress' : `practice/${key}`}">${access ? `Open ${title} →` : 'Preview membership'}</button></article>`).join('')}</section>${access ? '' : lockPanel('Activate membership to begin protected TCF, grammar and audio practice.')}`);
}
async function renderTcf(selected = 1) {
  if (!isActive()) { app.innerHTML = page('practice', lockPanel('The TCF Lab is available with an active membership.')); return; }
  try {
    if (!state.tcf) state.tcf = await (await fetch(apiUrl('/api/content/study/tcf.json'), { headers: { apikey: cfg.supabaseAnonKey, ...sessionHeaders() } })).json();
    const dossiers = state.tcf || []; const d = dossiers.find((item) => item.number === Number(selected)) || dossiers[0]; if (!d) throw new Error('No TCF dossier found.'); const qs = (d.questions || []).map((q, i) => questionCard({ prompt: q.prompt, choices: q.choices, answer: q.choices.find((c) => c.startsWith(`${q.answer}.`)) || q.answer }, `tcf-${d.number}-${i}`, 'TCF', d.number, 'TCF practice')).join('');
    app.innerHTML = page('practice', `<section class="practice-head"><div><button class="crumb" data-go="practice">← Practice</button><p class="eyebrow">TCF laboratory</p><h1>${esc(d.title)}</h1><p class="lead">Dossier ${String(d.number).padStart(2, '0')} · ${esc(d.level)} · ${d.questions?.length || 0} questions with immediate correction.</p></div><div class="dossier-picker">${dossiers.slice(0, 12).map((item) => `<button class="${item.number === d.number ? 'active' : ''}" data-go="practice/tcf/${item.number}">${item.number}</button>`).join('')}</div></section><section class="lesson-panel">${qs}<article class="reference-card"><div><p class="eyebrow">Source support</p><h3>Need the full strategy?</h3><p>The TCF book opens in a protected reader inside MOTIVA.</p></div><button class="button alt" data-reference="books/tcf.pdf" data-reference-title="Réussir le TCF facilement">Open reference</button></article></section>`);
  } catch { app.innerHTML = page('practice', `<section class="error-state"><h1>TCF Lab unavailable</h1><p>Please retry in a moment.</p></section>`); }
}
async function renderGrammar(level = 'A1') {
  if (!isActive()) { app.innerHTML = page('practice', lockPanel('Grammar Studio is available with an active membership.')); return; }
  try {
    if (!state.grammar) state.grammar = await (await fetch(apiUrl('/api/content/study/grammar.json'), { headers: { apikey: cfg.supabaseAnonKey, ...sessionHeaders() } })).json();
    const module = state.grammar.find((item) => item.level === String(level).toUpperCase()) || state.grammar[0]; const qs = (module.questions || []).map((q, i) => questionCard({ prompt: q.q, choices: q.choices, answer: q.answer, why: q.why }, `grammar-${module.level}-${i}`, 'GRAMMAR', module.level, 'Grammar drill')).join('');
    app.innerHTML = page('practice', `<section class="practice-head"><div><button class="crumb" data-go="practice">← Practice</button><p class="eyebrow">Grammar studio</p><h1>${esc(module.chapter)}</h1><p class="lead">Use a structure in context, then check it right away.</p></div><div class="level-tabs">${state.grammar.map((item) => `<button class="${item.level === module.level ? 'active' : ''}" data-go="practice/grammar/${item.level}">${item.level}</button>`).join('')}</div></section><section class="lesson-panel"><article class="grammar-map"><h2>Use this pattern</h2><ul>${(module.structures || []).map((item) => `<li>${esc(item)}</li>`).join('')}</ul></article>${qs}<article class="reference-card"><div><p class="eyebrow">Source support</p><h3>Read the full explanation</h3><p>The grammar guide is a protected in-platform reference.</p></div><button class="button alt" data-reference="books/grammar.pdf" data-reference-title="Le français, enfin compris !">Open reference</button></article></section>`);
  } catch { app.innerHTML = page('practice', `<section class="error-state"><h1>Grammar Studio unavailable</h1><p>Please retry in a moment.</p></section>`); }
}

function renderProgress() {
  if (!state.me?.user) { app.innerHTML = page('progress', lockPanel('Sign in to begin tracking your learning path.')); return; }
  const complete = totalCompleted(); const totalCorrect = Object.values(state.progress?.lessons || {}).reduce((sum, item) => sum + Object.keys(item.correct || {}).length, 0); const rows = LEVELS.map((level) => { const s = courseStats(level); const percent = Math.round((s.complete / 12) * 100); return `<article class="progress-course"><div><span>CEFR ${level}</span><h3>${esc(COURSE_PREVIEWS[level].label)}</h3><p>${s.complete} of 12 units complete · ${s.correct} correct practice responses</p></div><div class="progress-ring"><strong>${percent}%</strong></div></article>`; }).join('');
  app.innerHTML = page('progress', `<section class="page-intro"><p class="eyebrow">My progress</p><h1>Small sessions build fluency.</h1><p class="lead">This interface phase saves your lesson position and exercise successes on this device. Secure cross-device progress will be added in the next data phase.</p></section><section class="progress-overview"><article><strong>${complete}</strong><span>Lessons complete</span></article><article><strong>${totalCorrect}</strong><span>Correct responses</span></article><article><strong>${state.progress?.lastLesson ? `${state.progress.lastLesson.level} · ${String(state.progress.lastLesson.unit).padStart(2, '0')}` : '—'}</strong><span>Last lesson</span></article></section><section class="progress-list">${complete || totalCorrect ? rows : emptyProgress('Start an A1 lesson to see your learning trail here.')}</section>`);
}

function renderMembership() {
  if (!state.me?.user) { app.innerHTML = page('membership', `<section class="membership-layout"><div><p class="eyebrow">Membership</p><h1>Learn with protected access.</h1><p class="lead">Create your account, arrange manual payment or use an eligible 100% access code. Lessons, books and audio remain private until the server confirms access.</p><div class="membership-benefits"><span>✓ A1–C2 lesson pathways</span><span>✓ Inline listening and correction</span><span>✓ TCF and Grammar studios</span><span>✓ Protected in-platform references</span></div><button class="button" data-go="login">Create account / sign in</button></div><aside class="price-card"><span>MONTHLY ACCESS</span><strong>${state.plan?.configured ? money(state.plan.priceCents, state.plan.currency) : 'Available soon'}</strong><p>${fmt(state.plan?.instructions || 'Contact the course owner to arrange manual payment.')}</p>${state.plan?.contactUrl ? `<a class="button alt" href="${esc(state.plan.contactUrl)}" target="_blank" rel="noopener">${esc(state.plan.contactLabel || 'Contact the course owner')}</a>` : ''}</aside></section>`); return; }
  const access = state.me.access || {}; const activeLine = access.active ? `Active access via ${access.reason === 'admin' ? 'Admin account' : access.reason === 'promo_code' ? 'access code' : 'manual subscription'}${access.until ? ` until ${new Date(access.until).toLocaleString()}` : ', permanently'}.` : 'Your account does not have active access yet.';
  const panel = access.active ? `<section class="access-status active"><span>✓</span><div><h2>Your learning access is active</h2><p>${esc(activeLine)}</p><button class="button" data-go="today">Continue learning →</button></div></section>` : `<section class="access-status"><span>⌁</span><div><h2>Activate learning access</h2><p>${fmt(state.plan?.instructions || 'Contact the course owner to arrange manual payment. Access is activated after confirmation.')}</p>${state.plan?.contactUrl ? `<p><a class="button" href="${esc(state.plan.contactUrl)}" target="_blank" rel="noopener">${esc(state.plan.contactLabel || 'Contact the course owner')}</a></p>` : ''}<form id="checkout-form" class="promo-inline"><label>Have a 100% access code?<input name="code" autocomplete="off" placeholder="MOTIVA-…"></label><button class="button alt" type="submit">Apply code</button></form></div></section>`;
  app.innerHTML = page('membership', `<section class="page-intro narrow"><p class="eyebrow">Your membership</p><h1>Welcome, ${esc(state.me.user.email.split('@')[0])}.</h1><p class="lead">${esc(activeLine)}</p></section>${panel}<section class="membership-info"><article><span>01</span><h3>Choose your pathway</h3><p>Explore A1–C2 and identify your next useful lesson.</p></article><article><span>02</span><h3>Activate access</h3><p>Contact the owner using the configured manual payment method or redeem an eligible 100% code.</p></article><article><span>03</span><h3>Learn actively</h3><p>Protected lessons, audio and reference materials unlock after server-side verification.</p></article></section><div class="buttons"><button class="button red" id="logout">Sign out</button></div>`);
}

function adminTabs(current) { const tabs = [['admin', 'Overview'], ['admin/content', 'Content studio'], ['admin/people', 'Learners & access'], ['admin/coupons', 'Coupons & settings']]; return `<nav class="admin-tabs">${tabs.map(([key, label]) => `<button data-go="${key}" class="${current === key ? 'active' : ''}">${label}</button>`).join('')}</nav>`; }
function contentStudioPreview() { return `<section class="content-studio-preview"><div><p class="eyebrow">UI-only phase</p><h2>Content Studio is designed and ready for its data layer.</h2><p>These tools will become live after the additive content-model migration. No course, lesson, question or media record is created in this phase.</p></div><div class="studio-grid"><article><span>01</span><h3>Courses & units</h3><p>Order pathways, outcomes and availability.</p><button disabled>Manage courses</button></article><article><span>02</span><h3>Lessons</h3><p>Build sections: discover, listen, use, check and review.</p><button disabled>Manage lessons</button></article><article><span>03</span><h3>Exercises</h3><p>MCQ, fill blank, ordering, matching and listening checks.</p><button disabled>Manage exercises</button></article><article><span>04</span><h3>Media & references</h3><p>Associate private audio, visuals and book extracts.</p><button disabled>Manage media</button></article></div><p class="notice">The present interface continues to use the already-protected source curriculum. The next approved stage adds these controls without deleting current content.</p></section>`; }
async function renderAdmin(tab = 'admin') {
  if (!isAdmin()) { app.innerHTML = page('', `<section class="error-state"><h1>Admin access required</h1><p>This workspace is available only to the owner Admin account.</p></section>`); return; }
  try {
    state.admin = await api('/api/admin/overview'); const { plan, payment, promos = [], subscriptions: subs = [], grants = [] } = state.admin; const now = Date.now(); const active = subs.filter((s) => ['active', 'trialing'].includes(s.status) && (!s.current_period_end || Date.parse(s.current_period_end) > now)); const expired = subs.filter((s) => s.current_period_end && Date.parse(s.current_period_end) <= now); const toInput = (value) => value ? new Date(value).toISOString().slice(0, 16) : ''; const searchRows = (state.users || []).map((u) => `<tr><td>${esc(u.email)}</td><td><button class="text-button pick-user" data-id="${esc(u.user_id)}" data-email="${esc(u.email)}">Select</button></td></tr>`).join('') || '<tr><td colspan="2">Search by email to find a learner.</td></tr>'; const subRows = subs.map((s) => `<tr><td>${esc(s.profiles?.email || s.user_id)}</td><td>${esc(s.source || 'manual')}</td><td>${esc(s.status)}</td><td>${s.current_period_end ? esc(new Date(s.current_period_end).toLocaleString()) : '—'}</td><td>${['active','trialing'].includes(s.status) ? `<button class="text-button extend-subscription" data-user="${esc(s.user_id)}" data-start="${esc(s.current_period_start || '')}" data-end="${esc(s.current_period_end || '')}">Edit</button> <button class="text-button danger cancel-subscription" data-user="${esc(s.user_id)}">Cancel</button>` : '—'}</td></tr>`).join('') || '<tr><td colspan="5">No subscriptions yet.</td></tr>';
    const overview = `<section class="admin-summary"><article><strong>${active.length}</strong><span>Active members</span></article><article><strong>${expired.length}</strong><span>Expired memberships</span></article><article><strong>${promos.filter((p) => p.active).length}</strong><span>Active coupons</span></article><article><strong>6</strong><span>CEFR courses ready</span></article></section>`;
    const people = `<section class="admin-card"><div class="admin-section-head"><div><p class="eyebrow">Learners & access</p><h2>Find and activate a learner</h2></div></div><form id="user-search-form" class="form-grid"><div class="field"><label>Email search</label><input name="query" minlength="2" placeholder="learner@example.com" required></div><div class="field submit-field"><button class="button alt" type="submit">Search users</button></div></form><div class="table-wrap"><table class="admin-table"><thead><tr><th>Learner</th><th></th></tr></thead><tbody>${searchRows}</tbody></table></div><form id="manual-subscription-form" class="form-grid"><div class="field span-all"><label>Selected learner</label><input name="email" readonly placeholder="Search and select a learner"><input name="userId" type="hidden" required></div><div class="field"><label>Start date & time</label><input name="startsAt" type="datetime-local" value="${toInput(new Date())}" required></div><div class="field"><label>End date & time</label><input name="endsAt" type="datetime-local" required></div><div class="field submit-field"><button class="button" type="submit">Activate / update access</button></div></form></section><section class="admin-card"><h2>Membership overview</h2><div class="table-wrap"><table class="admin-table"><thead><tr><th>Learner</th><th>Source</th><th>Status</th><th>Ends</th><th>Action</th></tr></thead><tbody>${subRows}</tbody></table></div></section>`;
    const coupons = `<section class="admin-card"><p class="eyebrow">Membership settings</p><h2>Manual payment settings</h2><form id="plan-form" class="form-grid"><div class="field"><label>Monthly price in minor units</label><input name="priceCents" type="number" min="50" value="${esc(plan.priceCents || plan.price_cents || '')}" required></div><div class="field"><label>Currency</label><input name="currency" value="${esc(plan.currency || 'EGP')}" maxlength="3" required></div><div class="field submit-field"><button class="button" type="submit">Save monthly price</button></div></form><form id="payment-settings-form" class="form-grid"><div class="field span-all"><label>Instructions shown to non-subscribers</label><textarea name="instructions" required>${esc(payment.instructions || '')}</textarea></div><div class="field"><label>Contact button label</label><input name="contactLabel" value="${esc(payment.contactLabel || '')}" required></div><div class="field"><label>Contact URL</label><input name="contactUrl" value="${esc(payment.contactUrl || '')}" placeholder="https://wa.me/... or mailto:..."></div><div class="field submit-field"><button class="button" type="submit">Save payment details</button></div></form></section><section class="admin-card"><p class="eyebrow">Access codes</p><h2>Create a discount code</h2><form id="promo-form" class="form-grid"><div class="field"><label>Code</label><input name="code" placeholder="MOTIVA-GIFT" required></div><div class="field"><label>Discount %</label><input name="percentOff" type="number" min="1" max="100" required></div><div class="field"><label>Free duration days (100% only)</label><input name="freeDurationDays" type="number" min="1"></div><div class="field"><label>Maximum redemptions</label><input name="maxRedemptions" type="number" min="1"></div><div class="field"><label>Expires at</label><input name="validUntil" type="datetime-local"></div><div class="field submit-field"><button class="button" type="submit">Create code</button></div></form><div class="table-wrap"><table class="admin-table"><thead><tr><th>Code</th><th>Benefit</th><th>Limit</th><th>Status</th><th></th></tr></thead><tbody>${promos.map((p) => `<tr><td>${esc(p.code)}</td><td>${p.percent_off === 100 ? `100% · ${p.free_duration_days} days` : `${p.percent_off}% manual discount`}</td><td>${esc(p.max_redemptions || '—')}</td><td>${p.active ? 'Active' : 'Disabled'}</td><td><button class="text-button toggle-promo" data-id="${esc(p.id)}" data-active="${p.active ? '1' : '0'}">${p.active ? 'Disable' : 'Enable'}</button></td></tr>`).join('')}</tbody></table></div></section>`;
    let body = tab === 'admin/content' ? contentStudioPreview() : tab === 'admin/people' ? people : tab === 'admin/coupons' ? coupons : `${overview}<section class="admin-card"><p class="eyebrow">Learning platform</p><h2>Manage the learning experience</h2><p>The new dashboard, course flow and lesson player are live in this UI phase. Use Content Studio to see the planned authoring surfaces; database-backed authoring is intentionally held for the next approved phase.</p><div class="buttons"><button class="button" data-go="admin/content">Open Content Studio</button><button class="button alt" data-go="admin/people">Manage learners</button></div></section>`;
    app.innerHTML = page('admin', `<section class="admin-page-head"><p class="eyebrow">Owner control center</p><h1>Admin workspace</h1><p>Manage access today. Content authoring is visibly planned but does not write to the database in this phase.</p></section>${adminTabs(tab)}${body}`);
  } catch (error) { app.innerHTML = page('admin', `<section class="error-state"><h1>Admin data unavailable</h1><p>${esc(error.message)}</p></section>`); }
}

async function openReference(key, title) {
  try { const url = await protectedBlob(key); const old = document.getElementById('reference-reader'); if (old) old.remove(); const dialog = document.createElement('dialog'); dialog.id = 'reference-reader'; dialog.className = 'reference-reader'; dialog.innerHTML = `<div class="reader-top"><div><p class="eyebrow">Protected reference</p><h2>${esc(title || 'Reference')}</h2></div><button class="button alt" data-close-reader>Close</button></div><iframe title="${esc(title || 'Protected reference')}" src="${url}"></iframe>`; document.body.append(dialog); dialog.showModal(); } catch { setNotice('The protected reference could not be opened. Please check your active membership.', 'error'); render(); }
}
async function playProtected(key, button) { const url = await protectedBlob(key); if (state.activeAudio?.src === url && !state.activeAudio.paused) { state.activeAudio.pause(); button.classList.remove('playing'); button.querySelector('.audio-icon').textContent = '▶'; return; } if (state.activeAudio) state.activeAudio.pause(); document.querySelectorAll('.audio-control.playing').forEach((node) => { node.classList.remove('playing'); const icon = node.querySelector('.audio-icon'); if (icon) icon.textContent = '▶'; }); const audio = new Audio(url); state.activeAudio = audio; button.classList.add('playing'); button.querySelector('.audio-icon').textContent = '❚❚'; audio.onended = () => { button.classList.remove('playing'); button.querySelector('.audio-icon').textContent = '▶'; }; await audio.play(); }
function updateBuilder(id) { const builder = state.builders.get(id); const output = document.getElementById(`builder-output-${id}`); if (!builder || !output) return; output.innerHTML = builder.selected.length ? esc(sentenceFrom(builder.selected.map((index) => builder.tokens[index]))) : '<span>Tap words to build your sentence.</span>'; document.querySelectorAll(`[data-builder="${CSS.escape(id)}"][data-token]`).forEach((button) => { button.disabled = builder.selected.includes(Number(button.dataset.token)); }); }
function feedback(box, ok, message) { const out = box.querySelector('.feedback'); if (!out) return; out.textContent = message; out.className = `feedback ${ok ? 'ok' : 'no'}`; }
function activeLessonFromBox(box) { return { level: box.dataset.level, unit: Number(box.dataset.unit), exercise: box.dataset.exercise }; }

async function handleClick(event) {
  const target = event.target.closest('[data-go]'); if (target) { go(target.dataset.go); return; }
  const closeReader = event.target.closest('[data-close-reader]'); if (closeReader) { closeReader.closest('dialog')?.close(); closeReader.closest('dialog')?.remove(); return; }
  const audio = event.target.closest('[data-audio]'); if (audio) { try { await playProtected(audio.dataset.audio, audio); } catch { setNotice('Audio could not be loaded. Check your active membership.', 'error'); render(); } return; }
  const reference = event.target.closest('[data-reference]'); if (reference) { await openReference(reference.dataset.reference, reference.dataset.referenceTitle); return; }
  const stage = event.target.closest('[data-stage]'); if (stage) { const bits = route().split('/'); go(`lesson/${bits[1]}/${bits[2]}/${stage.dataset.stage}`); return; }
  const nextStage = event.target.closest('[data-stage-next]'); if (nextStage) { const bits = route().split('/'); const order = ['discover', 'listen', 'use', 'checkpoint', 'review']; const current = bits[3] || 'discover'; const next = nextStage.dataset.stageNext || order[Math.min(order.indexOf(current) + 1, order.length - 1)]; go(`lesson/${bits[1]}/${bits[2]}/${next}`); return; }
  const flip = event.target.closest('[data-flip-card]'); if (flip) { flip.classList.toggle('flipped'); return; }
  const mcq = event.target.closest('[data-check-mcq]'); if (mcq) { const box = mcq.closest('.exercise-card'); const picked = box.querySelector('input:checked'); if (!picked) { feedback(box, false, 'Choose an answer first.'); return; } const ok = picked.value === box.dataset.answer; feedback(box, ok, ok ? 'Correct — keep this pattern.' : 'Not quite. Review the correction, then try again.'); if (ok) { const x = activeLessonFromBox(box); markCorrect(x.level, x.unit, x.exercise); } return; }
  const fill = event.target.closest('[data-check-fill]'); if (fill) { const box = fill.closest('.exercise-card'); const input = box.querySelector('input'); const ok = normalText(input.value) === normalText(box.dataset.answer); feedback(box, ok, ok ? 'Correct — excellent retrieval.' : 'Check the correction and say the full phrase once.'); if (ok) { const x = activeLessonFromBox(box); markCorrect(x.level, x.unit, x.exercise); } return; }
  const match = event.target.closest('[data-check-match]'); if (match) { const box = match.closest('.exercise-card'); const selections = [...box.querySelectorAll('select[data-match-answer]')]; const ok = selections.length > 0 && selections.every((select) => select.value === select.dataset.matchAnswer); feedback(box, ok, ok ? 'All matches are correct.' : 'Some matches need another look.'); if (ok) { const x = activeLessonFromBox(box); markCorrect(x.level, x.unit, x.exercise); } return; }
  const token = event.target.closest('[data-token][data-builder]'); if (token) { const builder = state.builders.get(token.dataset.builder); if (builder && !builder.selected.includes(Number(token.dataset.token))) { builder.selected.push(Number(token.dataset.token)); updateBuilder(token.dataset.builder); } return; }
  const reset = event.target.closest('[data-reset-builder]'); if (reset) { const builder = state.builders.get(reset.dataset.resetBuilder); if (builder) { builder.selected = []; updateBuilder(reset.dataset.resetBuilder); } return; }
  const order = event.target.closest('[data-check-order]'); if (order) { const box = order.closest('.exercise-card'); const builder = state.builders.get(order.dataset.builder); const ok = normalText(sentenceFrom((builder?.selected || []).map((index) => builder.tokens[index]))) === normalText(order.dataset.answer); feedback(box, ok, ok ? 'Correct word order — read it aloud once.' : 'Try a different order, then check again.'); if (ok) { const x = activeLessonFromBox(box); markCorrect(x.level, x.unit, x.exercise); } return; }
  const dictation = event.target.closest('[data-check-dictation]'); if (dictation) { const box = dictation.closest('.exercise-card'); const input = box.querySelector('textarea'); const ok = normalText(input.value) === normalText(box.dataset.answer); feedback(box, ok, ok ? 'Excellent listening and writing.' : 'Compare your version with the transcript, then replay once.'); if (ok) { const x = activeLessonFromBox(box); markCorrect(x.level, x.unit, x.exercise); } return; }
  const complete = event.target.closest('[data-complete-lesson]'); if (complete) { const bits = route().split('/'); markComplete(bits[1], Number(bits[2])); setNotice('Lesson complete. Your next step is ready.'); go(Number(bits[2]) < 12 ? `lesson/${bits[1]}/${Number(bits[2]) + 1}` : 'progress'); return; }
  if (event.target.id === 'signup') { const form = document.getElementById('login-form'); try { await supabase('/auth/v1/signup', { method: 'POST', body: { email: form.email.value, password: form.password.value, options: { emailRedirectTo: location.href.split('#')[0] } } }); setNotice('Account created. Confirm your email if required, then sign in.'); renderLogin(); } catch (e) { setNotice(e.message, 'error'); renderLogin(); } return; }
  if (event.target.id === 'logout') { saveSession(null); state.me = null; loadProgress(); setNotice('Signed out.'); go('today'); return; }
  const toggle = event.target.closest('.toggle-promo'); if (toggle) { try { await api(`/api/admin/promos/${toggle.dataset.id}`, { method: 'PATCH', body: { active: toggle.dataset.active !== '1' } }); setNotice('Discount code status updated.'); await renderAdmin('admin/coupons'); } catch (e) { setNotice(e.message, 'error'); await renderAdmin('admin/coupons'); } return; }
  const pick = event.target.closest('.pick-user'); if (pick) { const form = document.getElementById('manual-subscription-form'); form.userId.value = pick.dataset.id; form.email.value = pick.dataset.email; form.endsAt.focus(); return; }
  const extend = event.target.closest('.extend-subscription'); if (extend) { const form = document.getElementById('manual-subscription-form'); form.userId.value = extend.dataset.user; const row = (state.admin?.subscriptions || []).find((item) => item.user_id === extend.dataset.user); form.email.value = row?.profiles?.email || extend.dataset.user; form.startsAt.value = extend.dataset.start ? new Date(extend.dataset.start).toISOString().slice(0, 16) : new Date().toISOString().slice(0, 16); form.endsAt.value = extend.dataset.end ? new Date(extend.dataset.end).toISOString().slice(0, 16) : ''; form.endsAt.focus(); return; }
  const cancel = event.target.closest('.cancel-subscription'); if (cancel) { if (!confirm('Cancel this manual subscription now? The learner will lose access immediately.')) return; try { await api(`/api/admin/subscriptions/${cancel.dataset.user}/cancel`, { method: 'POST' }); setNotice('Manual subscription cancelled.'); await renderAdmin('admin/people'); } catch (e) { setNotice(e.message, 'error'); await renderAdmin('admin/people'); } }
}
async function handleSubmit(event) {
  const form = event.target; event.preventDefault();
  if (form.id === 'login-form') { try { const data = await supabase('/auth/v1/token?grant_type=password', { method: 'POST', body: { email: form.email.value, password: form.password.value } }); saveSession(data); await getMe(); setNotice('Signed in successfully.'); go('today'); } catch (e) { setNotice(e.message, 'error'); renderLogin(); } return; }
  if (form.id === 'checkout-form') { try { const data = await api('/api/checkout', { method: 'POST', body: { code: form.code.value.trim() || undefined } }); if (data.freeAccess) { await getMe(); setNotice(`Free access activated until ${new Date(data.activeUntil).toLocaleString()}.`); go('today'); } else { const discount = data.discountPercent ? ` Your code ${data.code} provides ${data.discountPercent}% off; mention it when contacting the owner.` : ''; setNotice(`Manual payment information refreshed.${discount}`); state.plan = { ...state.plan, ...data }; renderMembership(); } } catch (e) { setNotice(e.message.replaceAll('_', ' '), 'error'); renderMembership(); } return; }
  if (form.id === 'plan-form') { try { await api('/api/admin/plan', { method: 'POST', body: { priceCents: Number(form.priceCents.value), currency: form.currency.value.trim().toUpperCase() } }); setNotice('Monthly manual-payment price saved.'); await getPlan(); await renderAdmin('admin/coupons'); } catch (e) { setNotice(e.message, 'error'); await renderAdmin('admin/coupons'); } return; }
  if (form.id === 'payment-settings-form') { try { await api('/api/admin/payment-settings', { method: 'POST', body: { instructions: form.instructions.value, contactLabel: form.contactLabel.value, contactUrl: form.contactUrl.value } }); setNotice('Payment instructions and contact method saved.'); await getPlan(); await renderAdmin('admin/coupons'); } catch (e) { setNotice(e.message, 'error'); await renderAdmin('admin/coupons'); } return; }
  if (form.id === 'user-search-form') { try { const data = await api(`/api/admin/users?query=${encodeURIComponent(form.query.value)}`); state.users = data.users || []; setNotice(`${state.users.length} matching learner(s) found.`); await renderAdmin('admin/people'); } catch (e) { setNotice(e.message, 'error'); await renderAdmin('admin/people'); } return; }
  if (form.id === 'manual-subscription-form') { try { await api('/api/admin/manual-subscriptions', { method: 'POST', body: { userId: form.userId.value, startsAt: new Date(form.startsAt.value).toISOString(), endsAt: new Date(form.endsAt.value).toISOString() } }); setNotice('Manual subscription saved.'); await renderAdmin('admin/people'); } catch (e) { setNotice(e.message, 'error'); await renderAdmin('admin/people'); } return; }
  if (form.id === 'promo-form') { try { const data = Object.fromEntries(new FormData(form)); await api('/api/admin/promos', { method: 'POST', body: { ...data, percentOff: Number(data.percentOff), freeDurationDays: data.freeDurationDays ? Number(data.freeDurationDays) : 0, maxRedemptions: data.maxRedemptions || undefined, validUntil: data.validUntil || undefined } }); setNotice('Discount code created.'); await renderAdmin('admin/coupons'); } catch (e) { setNotice(e.message, 'error'); await renderAdmin('admin/coupons'); } }
}
function renderLogin() { app.innerHTML = page('', `<section class="login-layout"><div><p class="eyebrow">Secure learner account</p><h1>Welcome to your French learning space.</h1><p class="lead">Sign in to continue lessons, keep device progress and access your membership.</p><div class="login-points"><span>✦ Continue where you stopped</span><span>◉ Practice with instant correction</span><span>♬ Protected listening inside lessons</span></div></div><section class="login-card"><h2>Sign in or create an account</h2><form id="login-form"><div class="field"><label>Email</label><input name="email" type="email" autocomplete="email" required></div><div class="field"><label>Password</label><input name="password" type="password" autocomplete="current-password" minlength="8" required></div><div class="buttons"><button class="button" type="submit">Sign in</button><button class="button alt" type="button" id="signup">Create account</button></div></form><p class="muted">New accounts may require email confirmation depending on the owner’s Supabase settings.</p></section></section>`); }
async function render() {
  const parts = route().split('/'); const main = parts[0];
  if (main === 'login') return renderLogin();
  if (main === 'today' || main === 'home') return renderToday();
  if (main === 'learn') return parts[1] && LEVELS.includes(parts[1]) ? renderCourse(parts[1]) : renderLearn();
  if (main === 'course' && LEVELS.includes(parts[1])) return renderCourse(parts[1]);
  if (main === 'lesson' && LEVELS.includes(parts[1]) && parts[2]) return renderLesson(parts[1], parts[2], parts[3]);
  if (main === 'practice') { if (parts[1] === 'tcf') return renderTcf(parts[2]); if (parts[1] === 'grammar') return renderGrammar(parts[2]); return renderPractice(); }
  if (main === 'progress') return renderProgress();
  if (main === 'membership' || main === 'account') return renderMembership();
  if (main === 'admin') return renderAdmin(parts[1] ? `admin/${parts[1]}` : 'admin');
  return renderToday();
}
async function boot() { try { saveSession(savedSession()); if (state.session) { try { await getMe(); } catch { saveSession(null); state.me = null; loadProgress(); } } else loadProgress(); await getPlan(); await render(); } catch (error) { app.innerHTML = `<section class="shell"><p class="error">Configuration error: ${esc(error.message)}</p><p>Set the public Supabase configuration before deploying.</p></section>`; } }
app.addEventListener('click', (event) => { handleClick(event); }); app.addEventListener('submit', (event) => { handleSubmit(event); }); window.addEventListener('hashchange', () => { render(); }); boot();
